-- Seed del catálogo: mismos datos que mock-catalog.ts del frontend
INSERT INTO genres (name) VALUES
    ('Action'), ('Supernatural'), ('Dark Fantasy'), ('Fantasy'), ('Drama'),
    ('Historical'), ('Adventure'), ('Comedy'), ('Sports'), ('Thriller'),
    ('Martial Arts'), ('Sci-Fi'), ('School'), ('Post-Apocalyptic'), ('Action Fantasy')
ON CONFLICT (name) DO NOTHING;

INSERT INTO entries (id, kind, slug, title, description, year, rating, episode_count, chapter_count, color, is_new, related_id) VALUES
    (1, 'anime', 'jujutsu-kaisen', 'Jujutsu Kaisen',
     'Yuji Itadori swallows a cursed finger and becomes host to the King of Curses, joining Tokyo Jujutsu High to hunt the curses that threaten humanity.',
     2024, 9.2, 24, NULL, '#7c3aed', true, NULL),
    (2, 'anime', 'demon-slayer', 'Demon Slayer',
     'After his family is slaughtered, Tanjiro joins the Demon Slayer Corps to cure his sister and hunt the demon who destroyed his life.',
     2024, 9.5, 11, NULL, '#dc2626', true, NULL),
    (3, 'anime', 'frieren', 'Frieren',
     'After the hero''s party defeats the Demon King, the elven mage Frieren embarks on a quiet journey to understand the humans she has outlived.',
     2023, 9.6, 28, NULL, '#0891b2', false, NULL),
    (4, 'anime', 'bleach-tybw', 'Bleach: TYBW',
     'Ichigo Kurosaki returns to the battlefield as the Quincy army led by Yhwach declares war on Soul Society.',
     2024, 9.3, 52, NULL, '#d97706', true, NULL),
    (5, 'anime', 'vinland-saga', 'Vinland Saga',
     'Thorfinn joins a band of mercenaries to avenge his father, only to learn that a warrior without a sword can still find redemption.',
     2023, 9.1, 24, NULL, '#7f5231', false, 17),
    (6, 'anime', 'spy-x-family', 'Spy x Family',
     'A master spy builds the perfect fake family, unaware that his daughter is a telepath and his wife an assassin.',
     2023, 8.7, 25, NULL, '#be185d', false, NULL),
    (7, 'anime', 'chainsaw-man', 'Chainsaw Man',
     'Denji fuses with his chainsaw devil Pochita and joins Public Safety''s devil hunters, chasing an ordinary life through extraordinary carnage.',
     2022, 8.8, 12, NULL, '#b91c1c', false, 19),
    (8, 'anime', 'attack-on-titan', 'Attack on Titan',
     'Humanity fights for survival behind towering walls against man-eating Titans in this brutal epic of freedom and war.',
     2023, 9.8, 87, NULL, '#374151', false, NULL),
    (9, 'anime', 'blue-lock', 'Blue Lock',
     'Japan locks 300 strikers in a brutal prison facility to forge the world''s most egotistical goalscorer.',
     2023, 8.5, 24, NULL, '#1d4ed8', true, NULL),
    (10, 'anime', 'one-piece', 'One Piece',
     'Monkey D. Luffy sails the Grand Line with his crew of pirates, chasing the legendary treasure and the throne of Pirate King.',
     2024, 9.0, 1100, NULL, '#d97706', false, NULL),
    (11, 'anime', 'my-hero-academia', 'My Hero Academia',
     'In a world of superpowers, quirkless Izuku Midoriya inherits the greatest power of all and enrolls in the top hero academy.',
     2024, 8.4, 138, NULL, '#16a34a', false, NULL),
    (12, 'anime', 'hunter-x-hunter', 'Hunter x Hunter',
     'Gon Freecss sets out to become a Hunter and find his missing father, meeting friends and monsters along the way.',
     2014, 9.4, 148, NULL, '#0891b2', false, NULL),
    (13, 'anime', 'death-note', 'Death Note',
     'A brilliant student finds a notebook that kills anyone whose name is written in it, and a cat-and-mouse game with the detective L begins.',
     2007, 9.3, 37, NULL, '#1e1b4b', false, NULL),
    (14, 'anime', 'fullmetal-alchemist', 'Fullmetal Alchemist',
     'Two brothers search for the Philosopher''s Stone to restore their bodies after a forbidden alchemical experiment goes wrong.',
     2010, 9.5, 64, NULL, '#7c2d12', false, NULL),
    (15, 'manga', 'berserk', 'Berserk',
     'Guts, a mercenary branded for sacrifice, swings his massive sword through a dark medieval world while hunting the demon who betrayed him.',
     2024, 9.7, NULL, 374, '#1c1917', false, NULL),
    (16, 'manga', 'vagabond', 'Vagabond',
     'The life of legendary swordsman Miyamoto Musashi, painted with brushstrokes as sharp as his blade.',
     2023, 9.5, NULL, 327, '#713f12', false, NULL),
    (17, 'manga', 'vinland-saga-manga', 'Vinland Saga',
     'A young Viking seeks revenge across the seas of England and Denmark, until the price of vengeance forces him to reimagine what a true warrior is.',
     2024, 9.2, NULL, 210, '#7f5231', false, 5),
    (18, 'manga', 'dungeon-meshi', 'Dungeon Meshi',
     'A dungeon-delving party must cook and eat the monsters they defeat to survive, in this delicious fantasy of food and friendship.',
     2023, 9.0, NULL, 97, '#15803d', false, NULL),
    (19, 'manga', 'chainsaw-man-2', 'Chainsaw Man Pt.2',
     'Asa Mitaka''s high school life collides with devils, fame and the War Devil''s plan to reclaim Chainsaw Man''s heart.',
     2024, 8.9, NULL, 155, '#b91c1c', true, 7),
    (20, 'manga', 'kaiju-no-8', 'Kaiju No. 8',
     'A cleanup worker who disposes of Kaiju corpses gains the power to become one, joining the Defense Force that hunts his own kind.',
     2024, 8.6, NULL, 120, '#0f4c81', true, NULL)
ON CONFLICT (id) DO NOTHING;

INSERT INTO entry_genres (entry_id, genre_id)
SELECT e.id, g.id FROM (VALUES
    (1, 'Action'), (1, 'Supernatural'),
    (2, 'Action'), (2, 'Fantasy'),
    (3, 'Fantasy'), (3, 'Drama'),
    (4, 'Action'), (4, 'Supernatural'),
    (5, 'Historical'), (5, 'Action'),
    (6, 'Comedy'), (6, 'Action'),
    (7, 'Dark Fantasy'), (7, 'Action'),
    (8, 'Action'), (8, 'Drama'),
    (9, 'Sports'), (9, 'Drama'),
    (10, 'Adventure'), (10, 'Action'),
    (11, 'Action'), (11, 'School'),
    (12, 'Action'), (12, 'Adventure'),
    (13, 'Thriller'), (13, 'Supernatural'),
    (14, 'Action'), (14, 'Fantasy'),
    (15, 'Dark Fantasy'), (15, 'Action'),
    (16, 'Historical'), (16, 'Martial Arts'),
    (17, 'Historical'), (17, 'Drama'),
    (18, 'Fantasy'), (18, 'Comedy'),
    (19, 'Dark Fantasy'), (19, 'Action'),
    (20, 'Action'), (20, 'Sci-Fi')
) AS seed(entry_slug_id, genre_name)
JOIN entries e ON e.id = seed.entry_slug_id
JOIN genres g ON g.name = seed.genre_name
ON CONFLICT DO NOTHING;

INSERT INTO hero_slides (id, entry_id, subtitle, description, position, palette) VALUES
    (1, 1, 'Season 3 · 2024',
     'As cursed spirits grow stronger, Yuji Itadori and his allies face their most dangerous battle yet against the fallen sorcerer Kenjaku and his Culling Game.',
     0, '{"from": "#2e1065", "to": "#4c1d95", "accent": "#a855f7", "textAccent": "#c084fc"}'),
    (2, 2, 'Infinity Castle Arc · 2024',
     'The final chapter unfolds as Tanjiro and the Hashira confront Muzan Kibutsuji in a breathtaking battle that will decide the fate of humanity.',
     1, '{"from": "#450a0a", "to": "#7f1d1d", "accent": "#f87171", "textAccent": "#fca5a5"}'),
    (3, 3, 'Season 1 · 2023',
     'A thousand-year-old elven mage sets out on a quiet journey to understand what it truly means to connect with others, long after her companions have passed.',
     2, '{"from": "#0c4a6e", "to": "#164e63", "accent": "#38bdf8", "textAccent": "#7dd3fc"}'),
    (4, 8, 'The Final Season Part 4 · 2023',
     'Eren Yeager unleashes the power of the Founding Titan, setting the world on an inevitable path toward total annihilation in the series'' epic conclusion.',
     3, '{"from": "#1c1917", "to": "#3d1f1f", "accent": "#a78bfa", "textAccent": "#c4b5fd"}')
ON CONFLICT (id) DO NOTHING;
