// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/animetest/backend/upload-service/internal/config"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitializeApp(cfg config.Config, router *gin.Engine) (*gin.Engine, error) {
	return router, nil
}
